// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  createdDate: __t.timestamp().name("created_date"),
  createdBy: __t.identity().name("created_by"),
  rows: __t.u8(),
  cols: __t.u8(),
  message: __t.string(),
  solution: __t.string(),
  grid: __t.string(),
});
