// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  Identity,
  ProductTypeElement,
  Timestamp,
} from "@clockworklabs/spacetimedb-sdk";

export type BoardDatabaseModel = {
  id: string,
  createdDate: Timestamp,
  createdBy: Identity,
  rows: number,
  cols: number,
  message: string,
  solution: string,
  grid: string,
};

/**
 * A namespace for generated helper functions.
 */
export namespace BoardDatabaseModel {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createStringType()),
      new ProductTypeElement("createdDate", AlgebraicType.createTimestampType()),
      new ProductTypeElement("createdBy", AlgebraicType.createIdentityType()),
      new ProductTypeElement("rows", AlgebraicType.createU8Type()),
      new ProductTypeElement("cols", AlgebraicType.createU8Type()),
      new ProductTypeElement("message", AlgebraicType.createStringType()),
      new ProductTypeElement("solution", AlgebraicType.createStringType()),
      new ProductTypeElement("grid", AlgebraicType.createStringType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: BoardDatabaseModel): void {
    BoardDatabaseModel.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): BoardDatabaseModel {
    return BoardDatabaseModel.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


