// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("GameSessionDatabaseModel", {
  id: __t.string(),
  boardId: __t.string(),
  startedDate: __t.timestamp(),
  playedBy: __t.identity(),
  finished: __t.bool(),
  isOnline: __t.bool(),
  foundWords: __t.string(),
});


