// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  boardId: __t.string().name("board_id"),
  startedDate: __t.timestamp().name("started_date"),
  playedBy: __t.identity().name("played_by"),
  finished: __t.bool(),
  isOnline: __t.bool().name("is_online"),
  foundWords: __t.string().name("found_words"),
});
