// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement,} from "@clockworklabs/spacetimedb-sdk";

export type GenerateNewBoard = {
  rows: number,
  cols: number,
  message: string,
  language: string,
};

/**
 * A namespace for generated helper functions.
 */
export namespace GenerateNewBoard {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("rows", AlgebraicType.createU8Type()),
      new ProductTypeElement("cols", AlgebraicType.createU8Type()),
      new ProductTypeElement("message", AlgebraicType.createStringType()),
      new ProductTypeElement("language", AlgebraicType.createStringType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: GenerateNewBoard): void {
    GenerateNewBoard.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): GenerateNewBoard {
    return GenerateNewBoard.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

