// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  boardId: __t.string().name("board_id"),
  direction: __t.string(),
  wordId: __t.string().name("word_id"),
  startRow: __t.u8().name("start_row"),
  startCol: __t.u8().name("start_col"),
  word: __t.string(),
});
