// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {deepEqual, TableCache,} from "@clockworklabs/spacetimedb-sdk";
import {WordPlacementsDatabaseModel} from "./word_placements_database_model_type";
 import type {EventContext} from ".";

/**
 * Table handle for the table `word`.
 *
 * Obtain a handle from the [`word`] property on [`RemoteTables`],
 * like `ctx.db.word`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.word.on_insert(...)`.
 */
export class WordTableHandle {
  tableCache: TableCache<WordPlacementsDatabaseModel>;

  constructor(tableCache: TableCache<WordPlacementsDatabaseModel>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<WordPlacementsDatabaseModel> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `id` unique index on the table `word`,
   * which allows point queries on the field of the same name
   * via the [`WordIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.word.id().find(...)`.
   *
   * Get a handle on the `id` unique index on the table `word`.
   */
  id = {
    // Find the subscribed row whose `id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): WordPlacementsDatabaseModel | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.id, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: WordPlacementsDatabaseModel) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: WordPlacementsDatabaseModel) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: WordPlacementsDatabaseModel) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: WordPlacementsDatabaseModel) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: WordPlacementsDatabaseModel, newRow: WordPlacementsDatabaseModel) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: WordPlacementsDatabaseModel, newRow: WordPlacementsDatabaseModel) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
